#' Plot Speaker Landscapes
#'
#' Takes the UMAP coordinates generated by \code{make_speaker_landscapes} and creates
#' a scatter plot visualizing the distribution of speakers, optionally colored
#' by category, and labeled by key word tokens.
#'
#' @param speaker_landscape A \code{list} object returned by the \code{make_speaker_landscapes}
#'   function, containing the UMAP-reduced coordinates for both speakers (\code{$speakers})
#'   and words (\code{$words}).
#' @param size_points A numeric value specifying the size of the speaker points in the plot.
#'   Defaults to \code{.3}.
#' @param alpha_points A numeric value specifying the transparency (alpha) of the
#'   speaker points in the plot. Defaults to \code{.3}.
#' @param categories Optional: A data frame or tibble with columns named \code{author}
#'   (containing speaker identifiers) and \code{categories} (containing the classification
#'   of the speakers). If provided, speakers will be colored by this column.
#'   Defaults to \code{NULL}.
#'
#' @return A \code{ggplot} object visualizing the UMAP reduction.
#'
#' @importFrom ggplot2 ggplot aes geom_point geom_text theme_minimal theme element_blank
#' @importFrom dplyr %>% mutate left_join
#'
#' @examples
#' \dontrun{
#' library(ggplot2)
#' library(dplyr)
#'
#' # --- Placeholder Data Structures (matching make_speaker_landscapes output) ---
#' # Assume 'landscape_data' was generated by make_speaker_landscapes()
#' landscape_data <- list(
#'   speakers = tibble::tibble(author = c("A", "B", "C", "D"), n_quotes = 10, X1 = 1:4, X2 = 4:1),
#'   words = tibble::tibble(words = c("cat", "dog"), X1 = c(2.5, 3.5), X2 = c(3.5, 2.5))
#' )
#'
#' # Example 1: Basic plot
#' plot_speaker_landscapes(landscape_data)
#'
#' # Example 2: Plot with categories
#' speaker_categories <- tibble::tibble(
#'   author = c("A", "B", "C", "D"),
#'   categories = c("Group 1", "Group 2", "Group 1", "Group 2")
#' )
#' plot_speaker_landscapes(landscape_data, categories = speaker_categories)
#' }
<<<<<<< HEAD
#' @export
=======
>>>>>>> ffdbbfbf087ca41a4c389908e4d45b4b513cdc19
plot_speaker_landscapes <- function(speaker_landscape,
                                    size_points = .3,
                                    alpha_points = .3,
                                    categories = NULL) {

  # Extract data from the list returned by make_speaker_landscapes
  df_final <- speaker_landscape$speakers
  low_dim_words <- speaker_landscape$words

  # Handle optional categories join
  if (!is.null(categories)) {
    # Assuming 'categories' has columns 'author' and 'categories'
    df_final <- df_final %>%
      dplyr::left_join(categories, by = "author")
  } else {
    # Create a dummy variable for color if no categories provided
    df_final <- df_final %>% dplyr::mutate(categories = "Uncategorized")
  }

  # --- Generate Plot ---
  plot_obj <- df_final %>%
    ggplot2::ggplot(ggplot2::aes(x = X1, y = X2)) +

    # Plot Speaker Points
    ggplot2::geom_point(ggplot2::aes(color = categories), size = size_points, alpha = alpha_points) +

    # Add Word Labels
    ggplot2::geom_text(
      data = low_dim_words,
      mapping = ggplot2::aes(x = X1, y = X2, label = words),
      inherit.aes = FALSE,
      check_overlap = TRUE,
      color = "black",
      size = 4,
      alpha = 1
    ) +

    # Apply Theme
    ggplot2::theme_minimal() +
    ggplot2::theme(
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.border = ggplot2::element_blank(),
      axis.line = ggplot2::element_blank(),
      axis.title.x = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      legend.position = if (is.null(categories)) "none" else "right" # Show legend only if categories are provided
    )

  return(plot_obj)
}
